server:
  port: ${PORT:5001}


spring:
  application:
    name: ROBOTUTOR-TECH-BACKEND
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL}
    password: ${PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  data:
    mongodb:
      uri: ${MONGODB_URL}/website-backend

app:
  config:
    from: ${spring.mail.username}
